<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="InputHandler" Version="1.2.0" />
    <PackageReference Include="Logging" Version="1.2.1" />
    <PackageReference Include="Rendering" Version="1.2.0" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.10" />
    <PackageReference Include="Telnet" Version="0.13.1" />
    <PackageReference Include="Transport" Version="1.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InputHandler\InputHandler.csproj" />
    <ProjectReference Include="..\Logging\Logging.csproj" />
    <ProjectReference Include="..\Parser\Parser.csproj" />
    <ProjectReference Include="..\Rendering\Rendering.csproj" />
    <ProjectReference Include="..\Transport\Transport.csproj" />
    <ProjectReference Include="..\Util\Util.csproj" />
    <!-- Kopiera alla JSON-filer i Resources och undermappar -->
    <Content Include="Resources\**\*.json" CopyToOutputDirectory="PreserveNewest" />

    <!-- Kopiera alla JSON-filer i Data och undermappar -->
    <Content Include="Data\**\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <None Update="csi.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="csiCommands.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="dcs.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="DcsBitGroups.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Esc%24.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="esc0.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="G0.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="G1.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="keymap.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Strings.en.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Strings.sv.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>