<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Parser</PackageId>
    <Version>1.2.1</Version>
    <Authors>Tomas Lundqvist</Authors>
    <PackageReadmeFile>Readme.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference
        Include="Logging"
        Version="1.2.1" />
    <PackageReference
        Include="Transport"
        Version="1.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <!-- Endast None, med rätt case och Pack=true -->
  <ItemGroup>
    <None
        Include="Data\**\*.*"
        Pack="true"
        PackagePath="contentFiles\any\any\data"
        PackageCopyToOutput="true"
        CopyToOutputDirectory="PreserveNewest" />

    <None
        Include="Resources\**\*.*"
        Pack="true"
        PackagePath="contentFiles\any\any\resources"
        PackageCopyToOutput="true"
        CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <None
        Include="buildTransitive\Parser.targets"
        Pack="true"
        PackagePath="buildTransitive\Parser.targets" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Readme.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>